# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import telemetry_pb2 as telemetry__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in telemetry_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TelemetryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamTelemetry = channel.stream_unary(
                '/telemetry.TelemetryService/StreamTelemetry',
                request_serializer=telemetry__pb2.OpticalFrame.SerializeToString,
                response_deserializer=telemetry__pb2.StreamResponse.FromString,
                _registered_method=True)


class TelemetryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamTelemetry(self, request_iterator, context):
        """StreamTelemetry pushes optical sensor data to the server in real-time.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TelemetryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamTelemetry': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamTelemetry,
                    request_deserializer=telemetry__pb2.OpticalFrame.FromString,
                    response_serializer=telemetry__pb2.StreamResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'telemetry.TelemetryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('telemetry.TelemetryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TelemetryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamTelemetry(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/telemetry.TelemetryService/StreamTelemetry',
            telemetry__pb2.OpticalFrame.SerializeToString,
            telemetry__pb2.StreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DSPServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamBatches = channel.stream_unary(
                '/telemetry.DSPService/StreamBatches',
                request_serializer=telemetry__pb2.FrameBatch.SerializeToString,
                response_deserializer=telemetry__pb2.DSPAck.FromString,
                _registered_method=True)


class DSPServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamBatches(self, request_iterator, context):
        """StreamBatches pushes consecutive FrameBatches to the Python DSP process.
        The stream runs from the lifetime of the DSP process; the Go side
        reconnects automatically if the Python process restarts.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DSPServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamBatches': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamBatches,
                    request_deserializer=telemetry__pb2.FrameBatch.FromString,
                    response_serializer=telemetry__pb2.DSPAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'telemetry.DSPService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('telemetry.DSPService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DSPService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamBatches(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/telemetry.DSPService/StreamBatches',
            telemetry__pb2.FrameBatch.SerializeToString,
            telemetry__pb2.DSPAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
