# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: telemetry.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'telemetry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftelemetry.proto\x12\ttelemetry\"N\n\x0cOpticalFrame\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x11\n\tsensor_id\x18\x02 \x01(\t\x12\x18\n\x10wavelength_shift\x18\x03 \x01(\x01\"!\n\x0eStreamResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"}\n\nFrameBatch\x12\'\n\x06\x66rames\x18\x01 \x03(\x0b\x32\x17.telemetry.OpticalFrame\x12\x11\n\tsensor_id\x18\x02 \x01(\t\x12\x17\n\x0fwindow_start_ns\x18\x03 \x01(\x03\x12\x1a\n\x12window_duration_ms\x18\x04 \x01(\x01\"4\n\x06\x44SPAck\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12\x18\n\x10rejection_reason\x18\x02 \x01(\t2[\n\x10TelemetryService\x12G\n\x0fStreamTelemetry\x12\x17.telemetry.OpticalFrame\x1a\x19.telemetry.StreamResponse(\x01\x32I\n\nDSPService\x12;\n\rStreamBatches\x12\x15.telemetry.FrameBatch\x1a\x11.telemetry.DSPAck(\x01\x42?Z=github.com/Clint-Mathews/PhotonicOps/services/ingestion-go/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'telemetry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z=github.com/Clint-Mathews/PhotonicOps/services/ingestion-go/pb'
  _globals['_OPTICALFRAME']._serialized_start=30
  _globals['_OPTICALFRAME']._serialized_end=108
  _globals['_STREAMRESPONSE']._serialized_start=110
  _globals['_STREAMRESPONSE']._serialized_end=143
  _globals['_FRAMEBATCH']._serialized_start=145
  _globals['_FRAMEBATCH']._serialized_end=270
  _globals['_DSPACK']._serialized_start=272
  _globals['_DSPACK']._serialized_end=324
  _globals['_TELEMETRYSERVICE']._serialized_start=326
  _globals['_TELEMETRYSERVICE']._serialized_end=417
  _globals['_DSPSERVICE']._serialized_start=419
  _globals['_DSPSERVICE']._serialized_end=492
# @@protoc_insertion_point(module_scope)
